CarsMangment/Models/Car.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations.Schema;

namespace CarsMangment.Models
{
    [Index(nameof(Car.CarNumber), IsUnique = true)]
    public class Car
    {
        public int Id { get; set; }
        
        public string CarNumber { get; set; } = null!;

        public string Type { get; set; } = null!;

        public int Capacity { get; set; }

        public string Color { get; set; } = null!;

        public double Fare { get; set; }

        public bool HasDriver { get; set; }

        public int? DriverId { get; set; }

        public int? CustomerId { get; set; }

        public virtual Customer? Customer { get; set; }

        public virtual Driver? Driver { get; set; }
    }
}

CarsMangment/Models/Customer.cs
namespace CarsMangment.Models
{
    public class Customer
    {
        public int Id { get; set; }

        public string Name { get; set; } = null!;
    }
}

CarsMangment/Models/Driver.cs
namespace CarsMangment.Models
{
    public class Driver
    {
        public int Id { get; set; }

        public string Name { get; set; } = null!;

        public bool? IsAbsence { get; set; }
    }
}

CarsMangment/Models/ErrorViewModel.cs
namespace CarsMangment.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CarsMangment/Controllers/CarsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CarsMangment.Data;
using CarsMangment.Models;
using System.Collections;
using CarsMangment.Services;

namespace CarsMangment.Controllers
{
    public class CarsController : Controller
    {
        private readonly CarBO _bo;
        private readonly ICacheService _cacheService;
        public CarsController(CarBO bo, ICacheService cacheService)
        {
            _bo = bo;
            _cacheService = cacheService;
        }

        // GET: Cars
        public IActionResult Index()
        {
            var cacheCars = _cacheService.GetData<IEnumerable<Car>>("cars") as List <Car>;
            if (cacheCars != null && cacheCars.Count() > 0)
                return View(cacheCars);
            var cars = _bo.GetCars();
            var expirtyTime=DateTimeOffset.Now.AddMinutes(2);
            _cacheService.SetData<IEnumerable<Car>>("cars", cars, expirtyTime);
            return View(cars);
        }

        // GET: Cars/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null )
            {
                return NotFound();
            }

            var car = await _bo.GetCarDetails(id.Value);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }
        // GET: Cars/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,CarNumber,Type,Capacity,Color,Fare,HasDriver,DriverId,CustomerId")] Car car)
        {
            if (ModelState.IsValid)
            {
                await _bo.Add(car);
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }


        // GET: Cars/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var car = await _bo.GetCarDetails(id.Value);
            if (car == null)
            {
                return NotFound();
            }
            return View(car);
        }

        // POST: Cars/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CarNumber,Type,Capacity,Color,Fare,HasDriver,DriverId,CustomerId")] Car car)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    var carnew= await _bo.Update(car);
                }
                catch (DbUpdateConcurrencyException)
                {
                   return NotFound();
                }
                return RedirectToAction(nameof(Index));
            }
            return View(car);
        }


        // GET: Cars/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {

            var car = await _bo.GetCarDetails(id.Value);
            if (car == null)
            {
                return NotFound();
            }

            return View(car);
        }

        // POST: Cars/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            var car = await _bo.GetCarDetails(id);
            if (car != null)
            {
                await _bo.Delete(id);
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

CarsMangment/Controllers/HomeController.cs
using CarsMangment.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CarsMangment.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CarsMangment/Views/Cars/Create.cshtml
@model CarsMangment.Models.Car

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Car</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CarNumber" class="control-label"></label>
                <input asp-for="CarNumber" class="form-control" />
                <span asp-validation-for="CarNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Capacity" class="control-label"></label>
                <input asp-for="Capacity" class="form-control" />
                <span asp-validation-for="Capacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fare" class="control-label"></label>
                <input asp-for="Fare" class="form-control" />
                <span asp-validation-for="Fare" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="HasDriver" /> @Html.DisplayNameFor(model => model.HasDriver)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="DriverId" class="control-label"></label>
                <select asp-for="DriverId" class ="form-control" asp-items="ViewBag.DriverId"></select>
            </div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <select asp-for="CustomerId" class ="form-control" asp-items="ViewBag.CustomerId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CarsMangment/Views/Cars/Delete.cshtml
@model CarsMangment.Models.Car

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Car</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Capacity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fare)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fare)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HasDriver)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HasDriver)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Driver)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Driver.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CarsMangment/Views/Cars/Details.cshtml
@model CarsMangment.Models.Car

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Car</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd readonly class="col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CarNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CarNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Capacity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Capacity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fare)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fare)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.HasDriver)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.HasDriver)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Driver)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Driver.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CarsMangment/Views/Cars/Edit.cshtml
@model CarsMangment.Models.Car

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Car</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input readonly asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarNumber" class="control-label"></label>
                <input asp-for="CarNumber" class="form-control" />
                <span asp-validation-for="CarNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control" />
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Capacity" class="control-label"></label>
                <input asp-for="Capacity" class="form-control" />
                <span asp-validation-for="Capacity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fare" class="control-label"></label>
                <input asp-for="Fare" class="form-control" />
                <span asp-validation-for="Fare" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="HasDriver" /> @Html.DisplayNameFor(model => model.HasDriver)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="DriverId" class="control-label"></label>
                <select asp-for="DriverId" class="form-control" asp-items="ViewBag.DriverId"></select>
                <span asp-validation-for="DriverId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label"></label>
                <select asp-for="CustomerId" class="form-control" asp-items="ViewBag.CustomerId"></select>
                <span asp-validation-for="CustomerId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CarsMangment/Views/Cars/Index.cshtml
@model IEnumerable<CarsMangment.Models.Car>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<div class="card">

    <div class="card-body">
        <a class="btn btn-success" asp-action="Create">Add New</a>
        <div class="card-title">
            <h2>Car Listing</h2>
        </div>

        <table class="table table-bordered table-striped" id='tbllist'>

            <thead class="bg-dark text-white">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Id)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CarNumber)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Type)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Capacity)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Color)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Fare)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.HasDriver)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Customer)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Driver)
                    </th>
                    <th>
                        Action
                    </th>
                </tr>
            </thead>
            <tbody>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CarNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Type)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Capacity)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Color)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Fare)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.HasDriver)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Customer.Id)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Driver.Id)
                        </td>
                        <td>
                            <a class="btn btn-primary" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                            <a class="btn btn-primary" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                            <a class="btn btn-danger" asp-action="Delete" asp-route-id="@item.Id">Delete</a>

                        </td>
                    </tr>
                }
            </tbody>

        </table>

    </div>

</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>
<style type="text/css">
    #tbllist_filter {
        margin-bottom: 1%;
    }
</style>
<script type="text/javascript">
    var js = jQuery.noConflict(true);
    js(document).ready(function () {
        js('#tbllist').DataTable({

        });
        //LoadListing();
    });

</script>

CarsMangment/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CarsMangment/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CarsMangment</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CarsMangment.styles.css" asp-append-version="true" />
    <link href="//cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CarsMangment</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cars" asp-action="Index">Car</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CarsMangment - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>